name: Test project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:21
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 21
      - run: npm ci
      - run: npm test
      - run: npm run build
